Feature/call hanging
P2Pulse/Pulse pull request #22
Opened 2022-09-17 15:52 UTC by yotamss

2022-09-17 16:01 UTC, GurGaller requested changes

2022-09-17 16:01 UTC, GurGaller commented on Pulse.Core/AudioStreaming/CallHanger.cs
> +        private async Task HangIfNoResponseForTooLongAsync()
I would separate this from the 0-based hangup. They are not related to one another, even though their side effect is the same

2022-09-17 16:01 UTC, GurGaller commented on Pulse.Core/AudioStreaming/CallHanger.cs
> +        private async Task HangIfNoResponseForTooLongAsync()
```suggestion
        private async Task HangUpIfNoResponseForTooLongAsync()
```

2022-09-17 16:01 UTC, GurGaller commented on Pulse.Core/AudioStreaming/CallHanger.cs
> +                    Console.WriteLine("Assuming connection lost, hanging up (without notifying the other side).");
But you are notifying the other side...

2022-09-17 16:06 UTC, GurGaller commented on Pulse.Core/AudioStreaming/CallHanger.cs
> +            while (true)
You need to stop this loop when the object is disposed

2022-09-17 16:13 UTC, merged

2022-09-18 20:24 UTC, yotamss commented on Pulse.Core/AudioStreaming/CallHanger.cs
> +        private async Task HangIfNoResponseForTooLongAsync()
later